
## Import file geodatabase into PostreSQL  

```{r setup, include=FALSE, cache=FALSE}
#Set root directory to R project root
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

Very often, landscape simulation models require the storage and processing of very large geospatial databases (10s to 100s of GB) that are downloaded as an ArcGIS geodatabase.

Because such large databases can be very difficult and time consuming to process in R, I typically store them in a PostgreSQL database with the PostGIS extension, and process them remotely by connecting to the database through R. 

The following is command line instructions for setting up a new PostGIS database and importing geospatial data stored as a file geodatabase. 

For information and instructions on downloading PostgreSQL and setting up the PostGIS extension, see, for example, [this tutorial](https://postgis.net/workshops/postgis-intro/installation.html). 

For this demonstration, we will be using the Alberta Derived Ecosite Phase database as our baseline natural land-cover database, which can be downloaded [here](https://open.alberta.ca/opendata/gda-ae37f83c-c994-47a9-b2f0-39ba1da0e64c). 



Unzip the files to the location of your choice. 


**In the Command Prompt Shell** 

To open the command prompt in Windows, type 'cmd' into the search bar at the bottom left of the screen, then hit Enter. 

Next, type in:  
> cmd.exe /c chcp 1252  
\n  
> cd C:\OSGeo4w64  

**Create the database**  
> createdb -U postgres st_sim_demo

**Connect to the database**  
> psql -d st_sim_demo -U postgres

**Add the PostGIS extension**  
> CREATE EXTENSION postgis;

**Close the command prompt shell and open the OSGeo4W Shell**  
*The shell will probably open in the C: drive. If that is not where your Postgres database is located, switch to the drive where it is located (for example, the D: drive)*  
\n   
> d:

**Load the geodatabase into the st_sim_demo database**  
\n   
> ogr2ogr -f "PostgreSQL" PG:"host=localhost port=5432 dbname=st_sim_demo user=postgres" D:\abc_program\projects\st-sim-risk-assessment-demo\0_data\raw\provincial_dep_v2.gdb -overwrite -progress --config PG_USE_COPY YES  

*Note: there will probably be a few error messages because of geometry type mismatches (Multisurface instead of Multipolygon). This seems like an inevitable consequence of converting the .gdb format into a simple features object in Postgres, and for this database there are only a few polygons lost.*    










